export const HERO_PHOTOS = [
  {
    id: 1,
    order: 0,
    x: "-340px",
    mobileX: "-240px",
    y: "10px",
    mobileY: "5px",
    rotate: -6,
    zIndex: 20,
    src: "/dev_travel/workparis2.webp",
    alt: "Photo 1",
  },
  {
    id: 2,
    order: 1,
    x: "-230px",
    mobileX: "-150px",
    y: "30px",
    mobileY: "20px",
    rotate: 3,
    zIndex: 30,
    src: "/dev_travel/workbogota.webp",
    alt: "Photo 2",
  },
  {
    id: 3,
    order: 2,
    x: "230px",
    mobileX: "150px",
    y: "5px",
    mobileY: "0px",
    rotate: -2,
    zIndex: 20,
    src: "/dev_travel/worksaopaulo.webp",
    alt: "Photo 3",
  },
  {
    id: 4,
    order: 3,
    x: "340px",
    mobileX: "240px",
    y: "25px",
    mobileY: "15px",
    rotate: 12,
    zIndex: 10,
    src: "/dev_travel/workreunion2.webp",
    alt: "Photo 4",
  },
] as const;
